Repository developer-challenge/pgs-study, pull requests merged in 2023-03, with the labels that each got.

#21 [jiseung-kang] lv.3/118667/Two-Pointer #19
  jiseung/lv3/118667.두 큐 합 같게 만들기.js
Labels: two pointer

#22 :sparkles: [sangtae365] gold3 / 1644. 소수의연속합 / 에라토스테네스의 체,투포인터
  sangtae/lv2/B1644_소수의연속합.java
Labels: two pointer, math

#25 [HojinAn] lv.2/42839/수학&구현
  hojin/lv2/42839 소수 찾기.js
Labels: brute force, math

#26 [HojinAn] lv.3/12979/수학&구현
  hojin/lv3/12979 기지국 설치.js
Labels: simulation, math

#27 [HojinAn] lv.2/68936/분할정복
  hojin/lv2/68936. 쿼드압축 후 개수 세기.js
Labels: divide&conquer

#28 :sparkles: [sangtae365] lv2 / 138476. 귤 고르기 / 해시, 구현
  .idea/.gitignore
  sangtae/.idea/.gitignore
  sangtae/lv2/P138476_귤고르기.java
Labels: simulation, hash

#31 [jiseung-kang] lv2 / 12914. 멀리뛰기 / math
  jiseung/lv2/12914.js
Labels: simulation, practice

#32 [jiseung-kang] lv2 / 138476. 귤 고르기 / 해시, 구현
  jiseung/lv2/138476.js
Labels: practice, hash

#35 :sparkles: [sangtae365] lv2 / 64065. 튜플 / 문자열, 구현
  sangtae/lv2/P64065_튜플.java
Labels: string, simulation

#36 [jiseung] lv2 / 42883. 큰 수 만들기/그리디
  jiseung/lv2/42883 큰 수 만들기.js
Labels: greedy

#37 [jiseung] lv2 / 42885. 구명보트/그리디
  jiseung/lv2/42885 구명보트.js
Labels: greedy

#39 [jiseung] lv3 / 42579. 베스트앨범/해시
  jiseung/lv3/42579. 베스트앨범.js
Labels: hash

#40 [jiseung] lv3 / 42861.섬 연결하기/그리디
  jiseung/lv3/42861.섬 연결하기.js
Labels: greedy, mst
