Repository developer-challenge/pgs-study, pull requests merged in 2023-02, with the labels that each got.

#3 [HojinAn] lv.2 / 42583. 다리를 지나는 트럭 / 큐
  hojin/lv2/42582 다리를 지나는 트럭.js
Labels: queue, simulation

#6 [sangtae365] lv.2 / 12981. 영어 끝말잇기
  sangtae/lv2/12981 영어 끝말잇기.java
Labels: simulation

#8 [Bori-github] lv.1 / 159994. 카드뭉치 / practice
  bori/lv1/159994.js
Labels: practice

#10 [Bori-github] lv.1 / 159994. 푸드 파이트 대회 / practice
  bori/lv1/134240.js
Labels: practice

#11 [HojinAn] lv.3 / 12987. 숫자 게임 / 투 포인터, 그리디
  hojin/lv3/12987 숫자 게임.js
Labels: greedy, two pointer, sort

#12 [HojinAn] lv.3/42579/해시
  hojin/lv3/.gitkeep
  hojin/lv3/42579 베스트앨범.js
Labels: sort, hash

#14 [jiseung-kang] Gold.IV/17404/DP #13
  jiseung/bj/17404.RGB거리2.js
Labels: dp

#15 [jiseung-kang] Gold.IV/14002/DP #13
  jiseung/bj/14002.js
Labels: dp

#16 :sparkles: [sangtae365] lv2 / 12980. 점프와 순간 이동 / 수학
  .idea/.gitignore
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  pgs-study.iml
  sangtae/lv2/P12980_점프와순간이동.java
Labels: math
